version: "3.9"
   
services:
  db:
    image: postgres:14.1
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
  frontend:
      build: ./frontend/
      volumes:
        - './frontend:/app'
        - '/app/node_modules'
      ports:
        - "3001:3000"
      environment:
        - CHOKIDAR_USEPOLLING=true
        - CI=true
        - NODE_ENV=development
        - env_file=.env
      command: npm start dev:watch